site_name: CÔNG CỤ & THỦ THUẬT
# site_url: http://127.0.0.1:8000/
repo_url: https://github.com/kcn97/cctt
repo_name: kcn97/cctt
edit_uri: blob/main/docs/
site_dir: public
nav:
  - Bắt đầu: index.md
  - Danh mục: danhmuc.md
  - Cộng tác:
      - Outlook: outlook.md
      - Calendar: calendar.md
      - OneDrive: onedrive.md
      - Zalo: zalo.md
      - Word: word.md
      - Excel: excel.md
      - Foxit PDF Reader: foxitpdfreader.md
      - Teams: teams.md
      - Canva: canva.md
      - CSDL: csdl.md
      - VnEdu: vnedu.md
      - Google: google.md
      - Edge: edge.md
      - M365 Copilot: m365copilot.md
      - VnEdu Teacher: vneduteacher.md
      - VnEdu Connect: vneduconnect.md
      - Forms: forms.md
      - SimpleMind: simplemind.md
      - Notion: notion.md
      - Directory Opus: directoryopus.md
  - Quản lý:
      - Outlook: outlook.md
      - Calendar: calendar.md
      - OneDrive: onedrive.md
      - Zalo: zalo.md
      - Word: word.md
      - Excel: excel.md
      - Foxit PDF Reader: foxitpdfreader.md
      - Teams: teams.md
      - Canva: canva.md
      - CSDL: csdl.md
      - VnEdu: vnedu.md
      - 10fastfingers: 10fastfingers.md
      - M365 Copilot: m365copilot.md
      - B&T PRO: b&tpro.md
      - Cam Scanner: camscanner.md
      - VnEdu Teacher: vneduteacher.md
      - VnEdu Connect: vneduconnect.md
      - QTranslate: qtranslate.md
      - WolframAlpha: wolframalpha.md
      - PowerPoint: powerpoint.md
      - Kutools for Excel: kutoolsforexcel.md
      - SimpleMind: simplemind.md
      - ReNamer: renamer.md
      - Notion: notion.md
      - UpNote: upnote.md
      - OBS Studio: obsstudio.md
      - Cobalt: cobalt.md
      - Groupy2: groupy2.md
  - Dạy học:
      - OneDrive: onedrive.md
      - Zalo: zalo.md
      - Word: word.md
      - Excel: excel.md
      - Foxit PDF Reader: foxitpdfreader.md
      - Teams: teams.md
      - Canva: canva.md
      - CSDL: csdl.md
      - VnEdu: vnedu.md
      - Google: google.md
      - Typing: typing.md
      - 10fastfingers: 10fastfingers.md
      - M365 Copilot: m365copilot.md
      - B&T PRO: b&tpro.md
      - Cam Scanner: camscanner.md
      - VnEdu Teacher: vneduteacher.md
      - VnEdu Connect: vneduconnect.md
      - MathType: mathtype.md
      - Genially: genially.md
      - Kutools for Excel: kutoolsforexcel.md
      - SimpleMind: simplemind.md
      - Notion: notion.md
      - UpNote: upnote.md
      - Anki: anki.md
      - Niagara Launcher: niagaralauncher.md
      - QRDex.io: qrdexio.md
      - Directory Opus: directoryopus.md
  - Hiệu suất:
      - Outlook: outlook.md
      - Calendar: calendar.md
      - OneDrive: onedrive.md
      - Zalo: zalo.md
      - Word: word.md
      - Excel: excel.md
      - Foxit PDF Reader: foxitpdfreader.md
      - Google: google.md
      - Edge: edge.md
      - Windows: windows.md
      - ChatGPT: chatgpt.md
      - Typing: typing.md
      - Listary: listary.md
      - M365 Copilot: m365copilot.md
      - Unikey: unikey.md
      - Todo: todo.md
      - Ditto: ditto.md
      - Renamer: renamer.md
      - Notion: notion.md
      - UpNote: upnote.md
      - Everything: everything.md
      - ShareX: sharex.md
      - Groupy2: groupy2.md
  - Dọn dẹp:
      - Delete Temporary Files: deletetemporaryfiles.md
      - QTranslate: qtranslate.md
      - WolframAlpha: wolframalpha.md
      - Everything: everything.md
      - Tree Size: treesize.md
      - Quotes Widget: quoteswidget.md
  - AI & Hỗ Trợ:
      - ChatGPT: chatgpt.md
      - M365 Copilot: m365copilot.md
      - PDF Eagle: pdfeagle.md
      - Mathpix: mathpix.md
      - UltraViewer: ultraviewer.md
      - Cobalt: cobalt.md
      - CapCut: capcut.md
  - Chủ đề:
      - Nhắc nhở: theme/nhacnho.md
      - Nút bấm: theme/nutbam.md
      - Tab nội dung: theme/tabnoidung.md
      - Chú thích: theme/chuthich.md
      - Định dạng: theme/dinhdang.md
      - Chú giải: theme/chugiai.md
theme:
    name: material
    custom_dir: overrides
    language: vi
    logo: assets/logo.png
    favicon: assets/favicon.ico
    icon:
        admonition:
                note: fontawesome/solid/note-sticky
                abstract: fontawesome/solid/book
                info: fontawesome/solid/circle-info
                tip: fontawesome/solid/bullhorn
                success: fontawesome/solid/check
                question: fontawesome/solid/circle-question
                warning: fontawesome/solid/triangle-exclamation
                failure: fontawesome/solid/bomb
                danger: fontawesome/solid/skull
                bug: fontawesome/solid/robot
                example: fontawesome/solid/flask
                quote: fontawesome/solid/quote-left 
        repo: fontawesome/brands/github
        edit: material/pencil
    features:
        - content.action.edit
        - content.code.copy
        - content.tabs.link           
        - search.suggest
        - search.highlight
        - search.share
        - header.autohide
        - announce.dismiss
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
        - navigation.indexes
        - navigation.sections
        - toc.follow
# When sections are enabled, top-level sections are rendered as groups in the sidebar for viewports above 1220px, but remain as-is on mobile.        
#       - navigation.sections
# When expansion is enabled, the left sidebar will expand all collapsible subsections by default, so the user doesn't have to open subsections manually.
#       - navigation.expand
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - bash
        - powershell
        - python
        - java
        - dos
        - javascript
        - json
        - css
        - html
        - http
        - tex
        - excel
        - django
        - curl
        - apache
        - awk
        - dockerfile
        - markdown
        - plaintext
        - pgsql
        - r
        - ruby
        - sql
        - shell
        - vba
        - vbscript
    palette:   
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode       
plugins:
    - tags
    - search:
        lang: vi
        separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
    - glightbox:
        touchNavigation: true
        loop: true
        effect: zoom
        slide_effect: slide
        width: 100%
        height: auto
        zoomable: true
        draggable: true
        skip_classes:
         - custom-skip-class-name
        auto_caption: true
        caption_position: bottom
    - git-revision-date-localized:
        enable_creation_date: true
        type: date
        fallback_to_build_date: true 
    - table-reader           
markdown_extensions:
  - pymdownx.snippets:
      auto_append:
      - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true    
  - abbr
  - attr_list
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true      
extra:
  # Custom translations
  language: vi  # Ensure Vietnamese is used as the base language
  # Custom translations for UI elements
  translate:
    # Change "Table of Contents" text 
    "toc.title": "Nội dung"
  # Disabled version provider to avoid 404 errors for versions.json
  # version:
  #   provider: mike
  #   default: stable  
extra_javascript:
  - javascripts/tablesort.min.js
  - javascripts/tablesort.js
extra_css:
  - stylesheets/extra.css